apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-notification
  namespace: todo-app
spec:
  template:
    spec:
      containers:
      - name: notification
        # Improve health check settings for notification service
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30   # Increased from 15
          periodSeconds: 15         # Increased from 10
          timeoutSeconds: 5         # Added timeout
          failureThreshold: 5       # Increased from 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 15   # Increased from 5
          periodSeconds: 10         # Increased from 5
          timeoutSeconds: 3         # Added timeout
          failureThreshold: 5       # Increased from 3
          successThreshold: 1
        # Slightly increase resource limits to handle load spikes
        resources:
          limits:
            cpu: 300m          # Increased from 200m
            memory: 384Mi      # Increased from 256Mi
          requests:
            cpu: 100m          # Increased from 50m
            memory: 192Mi      # Increased from 128Mi
---
# Add a PodDisruptionBudget to ensure availability during maintenance
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: notification-pdb
  namespace: todo-app
spec:
  minAvailable: 1  # Ensure the notification service remains available
  selector:
    matchLabels:
      app.kubernetes.io/component: notification
      app.kubernetes.io/instance: todo-app
      app.kubernetes.io/name: todo-app